name: my AWesome web
on: push
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      -  name: checkout repo
         uses: actions/checkout@v4

      -  name: Listing the files and Read 
         run: |
              echo "my first task"
              ls -ltra
              cat README.md

      #-  name: List the files
      #   run: ls

      #-  name: Read file
      #   run: cat README.md
