name: my AWesome web
on: push
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      -  name: checkout repo
         uses: actions/checkout@v4

      -  name: My first task
         run: echo "my first task"

      -  name: List the files
         run: ls

      -  name: Read file
         run: cat README.md
