name: Generate Ascii artwork 

on: push 

jobs:
   Ascii_artwork:
      runs-on: ubuntu-latest
      steps:
      -  name: checkout repo
         uses: actions/checkout@v4

      -  name: install cowsay package
         run: sudo apt-get install cowsay -y 

      -  name: Excecute cowsay program
         run: cowsay -f spider "Run for cover,  I am a spider........" >> spider.txt

      -  name: Test file exits
         run: grep -i "spider" spider.txt

      -  name: Read the files
         run: cat spider.txt
   
